framework:
  website: codeberg.org/fibers/fibers
  version: 1.3
language:
  engines:
    default:
      build_deps:
        - guile-fibers
        - build-essential
        - gcc
        - guile-3.0
        - guile-3.0-dev
