language:
  website: www.gnu.org/software/guile
  version: 3.0
  files:
    - "**/*.scm"
  engines:
    default:
      build_deps:
        - build-essential
        - gcc
        - guile-3.0
        - guile-3.0-dev

framework:
  engines:
    - default
  command: "guile -L . -e '('server')' -c '' $@"
  # byte-compilation at O3 improves the requests/s by 10% (default is O2)
  bootstrap:
    - guild compile -O3 server.scm -o server.go
